go(): move from bash_profile to functions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,5 +1,30 @@
 #!/bin/bash
 
+# present a project selector and change to the selected directory
+function go()
+{
+  local base=${1:-$PROJ_ROOT}
+  if [ -z "$base" ]; then
+    echo >&2 "error: PROJ_ROOT must be set or a base directory passed as the first argument"
+    return 1
+  fi
+
+  echo >&2 "(in $base)"
+  local findopts="-type d -maxdepth 4"
+  local excludes='.cocoapods|.vim/bundle'
+
+  # find -H -> follow symlinks
+  local dir=$(find -H $base $findopts -path '*/.git' 2>/dev/null | sed 's,/.git$,,' | grep -vE "$excludes" | xargs -I{} stat -f '%m %N' '{}' | sort -nr | sed -E 's,^[0-9]+ ,,' | sed -E "s,^$base/(src/)?,," | sed 's,/.git$,,' | selecta)
+
+  if [ -n "$dir" ]; then
+    local dest=$base/$dir
+    if [ ! -d "$dest" ]; then
+      dest=$base/src/$dir
+    fi
+    touch "$dest" && cd "$dest"
+  fi
+}
+
 # print the last touched file in this directory
 function lf()
 {
