Add some todogrep improvements (ht @alaroldai)

diff --git a/scripts/todogrep b/scripts/todogrep
--- a/scripts/todogrep
+++ b/scripts/todogrep
@@ -9,18 +9,30 @@
 # Options:
 #   -i <pattern>    Include files matching <pattern> (multiple patterns can be specified)
 #   -e <pattern>    Exclude files matching <pattern> (multiple patterns can be specified)
-#   -f <format>     Format output: use 'warn' to format like a compiler warning (also preventing a non-zero exit status)
-#   -m <mode>       Search mode: defaults to 'git', and falls back to recursively searching files in the current directory
+#   -f <format>     Format output: use 'warn' to format like a compiler warning (also preventing a non-zero exit status).
+#                   Default value is 'none'.
+#   -m <mode>       Search mode: defaults to 'git', and falls back to recursively searching files in the current directory.
+#                   You can also specify 'find' to perform a recursive search relative to the current working directory.
 
 ## Finding files
 
 find_files() {
   search_mode=$1
 
-  if [ "${search_mode}" = "git" ] && in_git_dir; then
+  if [ "${search_mode}" != "git" ]; then
+    if in_git_dir
+    then true # no-op
+    else search_mode="find"
+    fi
+  fi
+
+  if [ "${search_mode}" = "git" ]; then
     git ls-files
-  else
+  elif [ "${search_mode}" = "find" ]; then
     find . -type f | sed 's/^.\///'
+  else
+    echo "todogrep: unsupported file search mode '${search_mode}'" >&2
+    exit 1
   fi
 }
 
@@ -44,11 +56,15 @@ format_results() {
   mode=$1; shift
 
   case ${mode} in
-    warn|xcode)
+    warn)
       format_warn ${*}
       ;;
-    *)
+    none)
       cat
+      ;;
+    *)
+      echo "todogrep: unsupported format mode '${mode}'" >&2
+      exit 1
       ;;
   esac
 }
@@ -73,7 +89,7 @@ fail_on_output() {
 
 declare -a includes
 declare -a excludes
-declare format_mode="default"
+declare format_mode="none"
 declare search_mode="git"
 declare keywords="FIXME:|TODO:"
 
@@ -97,6 +113,8 @@ while getopts e:i:f:m: opt; do
 done
 
 shift $((OPTIND - 1))
+
+set -o pipefail
 
 find_files ${search_mode} \
   | accept_paths ${includes[*]} \
